### ISSUE TITLE
RISC-V Forth

### ISSUE THREAD

**Issue by larsbrinkhoff** [riscv/riscv-wiki#1]
Not sure if it's appropriate for the "Software Status" page on this wiki, but I have ported my Forth to RISC-V.  It targets the RV32IM instruction set, version 2.0.  There's a Forth-flavoured RISC-V assembler, and a compiler to rebuild itself.

https://github.com/larsbrinkhoff/lbForth  
https://github.com/larsbrinkhoff/lbForth/tree/master/targets/riscv

**Comment by sorear** [comment]
Forth kernels should probably be their own category, I know of 3 at this point (yours, muforth, Kestrel eForth)

**Comment by larsbrinkhoff** [comment]
Here's muforth:  
https://github.com/nimblemachines/muforth  
https://github.com/nimblemachines/muforth/tree/master/mu/target/RISC-V

**Comment by sorear** [comment]
I went ahead and added muforth and lbforth to the page in a new category @nimblemachines.

@sam-falvo should eforth be on the list?

**Comment by sam-falvo** [comment]
You can put it there, I suppose; however, I've not taken the time to package it up as a shrink-wrapped thing someone can just download and install.  My version of eForth is built for the needs of my Kestrel project (e.g., it assumes the CPU cold-boots at $FFFFFFFFFFFFFF00).  It's not hard to build as long as you have the right dependencies installed (which are documented in the Kestrel-3 User's Guide at the moment).  It's mostly written in 64-bit GForth 0.7, so it should be fairly easy to tailor to your specific needs.

I'd be happy to help anyone who's interested in tweaking the code, and contributions/patches to enhance portability are always welcome.

**Comment by sam-falvo** [comment]
I should note, as well, that my version of eForth is coded to produce a raw binary file; it does not yield an ELF executable.  My port assumes it's booting on bare metal.

**Comment by larsbrinkhoff** [comment]
There is now a port of Mecrisp to RISC-V:

https://groups.google.com/forum/#!topic/comp.lang.forth/bi1Baa82KDI
