### ISSUE TITLE
CompCert Software Status

### ISSUE THREAD

**Issue by bschommer** [riscv/riscv-wiki#3]
It seems that the Software status page for CompCert is not up to date. The Maintainer should be Xavier Leroy and the Link to the ```RISC-V repository``` does not work.

**Comment by gurjeet** [comment]
@bschommer Can you please mention the Wiki Page as well as the link-text that need to be updated.

**Comment by bschommer** [comment]
On this [https://github.com/riscv/riscv-wiki/wiki/RISC-V-Software-Status#compcert](page). The maintainer should be Xavier Leroy (INRIA) and the RISC-V repository link should be removed since it no longer works.

**Comment by arunthomas** [comment]
I removed the outdated link. I believe Prahsant is maintaining the RISC-V port?

**Comment by bschommer** [comment]
The RISC-V port was merged upstream, I don't now the policy for this case but it also seems that the repository of Prahsant is kind of outdated.

**Comment by arunthomas** [comment]
Ok, I'll update the maintainer to be Xavier. Thanks for the note.
